### ISSUE TITLE
[BUG] Mod prevents OP's from joining servers

### ISSUE THREAD

**Issue by Darkere** [Quarris/EnigmaticGraves#46]
**Describe the bug**

When Enigmatic Graves is installed, opping someone kicks them and OP's can no longer join a server

**Versions (please complete the following information):**
 - Minecraft-Mod: EnigmaticGraves-1.19.2-1.7.4
 - Forge: 43.1.34

Error is due to broken packet. See https://github.com/EnigmaticaModpacks/Enigmatica9/issues/73 for full log

```
[12Oct2022 06:45:18.729] [Netty Client IO #1/DEBUG] [net.minecraft.network.Connection/]: Failed to sent packet
io.netty.handler.codec.DecoderException: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:ation
 targets  players?
vehicle?
cart1 carts ?
cart1 cart?
set t
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:480) ~[netty-codec-4.1.77.Final.jar%23103!/:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[netty-codec-4.1.77.Final.jar%23103!/:4.1.77.Final]
````

**Comment by Quarris** [comment]
EG doesnt use any packets at all

**Comment by Darkere** [comment]
This happens with just forge and eg installed. Only thing I could imagine causing it is the grave commands

**Comment by Quarris** [comment]
Ok that is wack. Ill check it out in the morning
